# =============================================================================
# L2 Platform Layer Configuration
# =============================================================================
# Singleton layer providing platform services (Vault, Casdoor, Dashboard, etc.)
# Shared by all environments (staging and prod both depend on this single instance)

include "root" {
  path = find_in_parent_folders()
}

# =============================================================================
# Generate providers.tf
# =============================================================================
# Providers specific to L2 platform layer

generate "layer_providers" {
  path      = "providers_layer.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOF
    # L2 Platform Layer-Specific Providers
    # Common providers (kubernetes, helm, vault, kubectl) are generated by root terragrunt.hcl

    provider "cloudflare" {
      api_token = var.cloudflare_api_token
    }

    # Cloudflare zone data source for internal domain (used by Casdoor DNS)
    data "cloudflare_zone" "internal" {
      name = local.internal_domain
    }
  EOF
}

# =============================================================================
# Generate required_providers in versions.tf
# =============================================================================

generate "layer_required_providers" {
  path      = "versions.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOF
    terraform {
      required_version = ">= 1.11.0"

      required_providers {
        # Common providers (from root terragrunt.hcl)
        kubernetes = {
          source  = "hashicorp/kubernetes"
          version = "~> 2.0"
        }
        helm = {
          source  = "hashicorp/helm"
          version = "~> 2.0"
        }
        vault = {
          source  = "hashicorp/vault"
          version = "~> 4.0"
        }
        random = {
          source  = "hashicorp/random"
          version = "~> 3.6"
        }
        kubectl = {
          source  = "alekc/kubectl"
          version = "~> 2.0"
        }

        # L2 Platform layer-specific providers
        cloudflare = {
          source  = "cloudflare/cloudflare"
          version = "~> 4.0"
        }
        null = {
          source  = "hashicorp/null"
          version = "~> 3.2"
        }
        restapi = {
          source  = "Mastercard/restapi"
          version = "1.20.0"
        }
        time = {
          source  = "hashicorp/time"
          version = "~> 0.11"
        }
      }
    }
  EOF
}
