# =============================================================================
# L2 Platform Layer Configuration
# =============================================================================
# Singleton layer providing platform services (Vault, Casdoor, Dashboard, etc.)
# Shared by all environments (staging and prod both depend on this single instance)

include "root" {
  path = find_in_parent_folders()
}

# =============================================================================
# Generate providers.tf
# =============================================================================
# Providers specific to L2 platform layer

generate "layer_providers" {
  path      = "providers_layer.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOF
    # L2 Platform Layer-Specific Providers
    # Common providers (kubernetes, helm, vault) are generated by root terragrunt.hcl

    provider "kubectl" {
      config_path      = var.kubeconfig_path != "" ? var.kubeconfig_path : null
      load_config_file = var.kubeconfig_path != ""
    }

    provider "cloudflare" {
      api_token = var.cloudflare_api_token
    }

    # Cloudflare zone data source for internal domain (used by Casdoor DNS)
    data "cloudflare_zone" "internal" {
      name = local.internal_domain
    }
  EOF
}

# =============================================================================
# Generate required_providers in versions.tf
# =============================================================================

generate "layer_required_providers" {
  path      = "versions_providers_layer.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOF
    terraform {
      required_providers {
        # Common providers (kubernetes, helm, vault, random) defined in root terragrunt.hcl

        # L2 Platform layer-specific providers
        cloudflare = {
          source  = "cloudflare/cloudflare"
          version = "~> 4.0"
        }
        kubectl = {
          source  = "alekc/kubectl"
          version = "~> 2.0"
        }
        null = {
          source  = "hashicorp/null"
          version = "~> 3.2"
        }
        restapi = {
          source  = "Mastercard/restapi"
          version = "1.20.0"
        }
        time = {
          source  = "hashicorp/time"
          version = "~> 0.11"
        }
      }
    }
  EOF
}
