# ============================================================
# SigNoz Observability Stack
# Deploys metrics, traces, and logs platform to L4
#
# Architecture (MVP):
# - L4 singleton control plane
# - Uses bundled ClickHouse + Zookeeper (self-contained)
# - TODO: Migrate to L3 ClickHouse with cluster support
#
# Note: External ClickHouse requires cluster configuration.
# L3 ClickHouse is single-node without cluster support.
# For MVP, using SigNoz bundled ClickHouse for simplicity.
# ============================================================

# Import existing namespace for idempotency
import {
  to = kubernetes_namespace.observability
  id = "observability"
}

# Import existing SigNoz helm release (deployed via PR #325)
import {
  to = helm_release.signoz
  id = "observability/signoz"
}

# Read SigNoz credentials from Vault (generated by L2)
data "vault_kv_secret_v2" "signoz_clickhouse" {
  mount = var.vault_kv_mount
  name  = "signoz"
}

# ============================================================
# Observability Namespace
# ============================================================
resource "kubernetes_namespace" "observability" {
  metadata {
    name = "observability"
    labels = {
      "layer" = "L4"
    }
  }
}

# ============================================================
# SigNoz Helm Release
# Chart: https://charts.signoz.io
# ============================================================
resource "helm_release" "signoz" {
  name       = "signoz"
  namespace  = kubernetes_namespace.observability.metadata[0].name
  repository = "https://charts.signoz.io"
  chart      = "signoz"
  version    = "0.52.0" # Pin version for reproducibility

  wait          = false # Don't wait - SigNoz has complex startup dependencies
  wait_for_jobs = false
  timeout       = 600 # 10 minutes

  values = [yamlencode({
    # ============================================================
    # Bundled ClickHouse (MVP)
    # Note: For production, integrate with L3 external ClickHouse
    # TODO: Configure L3 ClickHouse with cluster support for SigNoz
    # ============================================================
    clickhouse = {
      enabled = true
      # Minimal resources for MVP
      resources = {
        requests = { cpu = "100m", memory = "256Mi" }
        limits   = { cpu = "500m", memory = "1Gi" }
      }
      persistence = {
        enabled = true
        size    = "10Gi"
      }
      # Zookeeper for ClickHouse cluster support
      zookeeper = {
        enabled = true
        image = {
          registry   = "docker.io"
          repository = "bitnamilegacy/zookeeper" # bitnami moved to bitnamilegacy
          tag        = "3.9.3-debian-12-r22"
        }
        resources = {
          requests = { cpu = "50m", memory = "128Mi" }
          limits   = { cpu = "200m", memory = "256Mi" }
        }
      }
    }

    # ============================================================
    # Frontend configuration
    # ============================================================
    frontend = {
      service = {
        port = 3301
      }
      ingress = {
        enabled   = true
        className = "traefik"
        hosts = [{
          host = "signoz.${var.internal_domain}"
          paths = [{
            path     = "/"
            pathType = "Prefix"
            port     = 3301
          }]
        }]
        tls = [{
          secretName = "wildcard-tls-internal"
          hosts      = ["signoz.${var.internal_domain}"]
        }]
      }
    }

    # Query service - lighter resources since ClickHouse is external
    queryService = {
      resources = {
        requests = { cpu = "100m", memory = "256Mi" }
        limits   = { cpu = "500m", memory = "512Mi" }
      }
    }

    # OTel Collector
    otelCollector = {
      resources = {
        requests = { cpu = "100m", memory = "256Mi" }
        limits   = { cpu = "500m", memory = "512Mi" }
      }
    }
  })]

  depends_on = [kubernetes_namespace.observability]
}

# ============================================================
# Outputs
# ============================================================
output "signoz_url" {
  description = "SigNoz UI URL"
  value       = "https://signoz.${var.internal_domain}"
}

output "signoz_otel_endpoint" {
  description = "OpenTelemetry collector endpoint for applications"
  value       = "signoz-otel-collector.observability.svc.cluster.local:4317"
}
