# ============================================================
# SigNoz Observability Stack
# Deploys metrics, traces, and logs platform to L4
#
# Architecture:
# - L4 singleton control plane
# - Uses L3 ClickHouse (data-staging namespace)
# - Dedicated signoz user with limited DB permissions
# ============================================================

# Import existing namespace for idempotency
import {
  to = kubernetes_namespace.observability
  id = "observability"
}

# Read SigNoz credentials from Vault (generated by L2)
data "vault_kv_secret_v2" "signoz_clickhouse" {
  mount = var.vault_kv_mount
  name  = "signoz"
}

# ============================================================
# Observability Namespace
# ============================================================
resource "kubernetes_namespace" "observability" {
  metadata {
    name = "observability"
    labels = {
      "layer" = "L4"
    }
  }
}

# ============================================================
# SigNoz Helm Release
# Chart: https://charts.signoz.io
# ============================================================
resource "helm_release" "signoz" {
  name       = "signoz"
  namespace  = kubernetes_namespace.observability.metadata[0].name
  repository = "https://charts.signoz.io"
  chart      = "signoz"
  version    = "0.52.0" # Pin version for reproducibility

  wait    = true
  timeout = 600 # 10 minutes

  values = [yamlencode({
    # ============================================================
    # External ClickHouse Configuration
    # Disable ALL bundled ClickHouse components - use L3 external
    # ============================================================
    clickhouse = {
      enabled = false  # Disable bundled ClickHouse entirely
    }

    # Disable zookeeper (only needed for bundled ClickHouse)
    zookeeper = {
      enabled = false
    }

    # Disable ClickHouse operator (only needed for bundled ClickHouse)
    clickhouse-operator = {
      enabled = false
    }

    # ============================================================
    # External ClickHouse Connection for all services
    # ============================================================
    externalClickhouse = {
      host        = "clickhouse.data-staging.svc.cluster.local"
      httpPort    = 8123
      tcpPort     = 9000
      user        = data.vault_kv_secret_v2.signoz_clickhouse.data["username"]
      password    = data.vault_kv_secret_v2.signoz_clickhouse.data["password"]
      database    = "signoz_traces"
      cluster     = "default"  # Required by SigNoz chart
      secure      = false
    }

    # ============================================================
    # Frontend configuration
    # ============================================================
    frontend = {
      service = {
        port = 3301
      }
      ingress = {
        enabled   = true
        className = "traefik"
        hosts = [{
          host = "signoz.${var.internal_domain}"
          paths = [{
            path     = "/"
            pathType = "Prefix"
            port     = 3301
          }]
        }]
        tls = [{
          secretName = "wildcard-tls-internal"
          hosts      = ["signoz.${var.internal_domain}"]
        }]
      }
    }

    # Query service - lighter resources since ClickHouse is external
    queryService = {
      resources = {
        requests = { cpu = "100m", memory = "256Mi" }
        limits   = { cpu = "500m", memory = "512Mi" }
      }
    }

    # OTel Collector
    otelCollector = {
      resources = {
        requests = { cpu = "100m", memory = "256Mi" }
        limits   = { cpu = "500m", memory = "512Mi" }
      }
    }
  })]

  depends_on = [kubernetes_namespace.observability]
}

# ============================================================
# Outputs
# ============================================================
output "signoz_url" {
  description = "SigNoz UI URL"
  value       = "https://signoz.${var.internal_domain}"
}

output "signoz_otel_endpoint" {
  description = "OpenTelemetry collector endpoint for applications"
  value       = "signoz-otel-collector.observability.svc.cluster.local:4317"
}
