# =============================================================================
# L4 Apps Layer Configuration - Singleton
# =============================================================================
# Control plane layer (Kubero GitOps, SigNoz observability)
# Deployed as singleton - manages workloads across all environments
# Environment separation is handled at application level (Kubero Pipeline/Phase)

include "root" {
  path = find_in_parent_folders()
}

# =============================================================================
# Layer Dependencies
# =============================================================================
# L4 depends on L2 (platform) for infrastructure services

dependency "platform" {
  config_path = "../2.platform"

  mock_outputs = {
    vault_address = "http://vault.platform.svc.cluster.local:8200"
  }
  mock_outputs_allowed_terraform_commands = ["validate", "plan"]
}

# =============================================================================
# Layer-Specific Providers
# =============================================================================
# Common providers (kubernetes, helm, vault, random) are generated by root terragrunt.hcl

generate "layer_providers" {
  path      = "providers_layer.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOF
    # L4 Apps Layer-Specific Providers

    provider "kubectl" {
      config_path      = var.kubeconfig_path != "" ? var.kubeconfig_path : null
      load_config_file = var.kubeconfig_path != ""
    }
  EOF
}

# =============================================================================
# Layer-Specific Required Providers
# =============================================================================
# Common providers (kubernetes, helm, vault, random) defined in root terragrunt.hcl

generate "layer_required_providers" {
  path      = "versions_providers_layer.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOF
    terraform {
      required_providers {
        kubectl = {
          source  = "alekc/kubectl"
          version = "~> 2.0"
        }
      }
    }
  EOF
}
