# =============================================================================
# L4 Apps Layer Configuration - Singleton
# =============================================================================
# Control plane layer (Kubero GitOps, SigNoz observability)
# Deployed as singleton - manages workloads across all environments
# Environment separation is handled at application level (Kubero Pipeline/Phase)

include "root" {
  path = find_in_parent_folders()
}

# =============================================================================
# Layer Dependencies
# =============================================================================
# L4 depends on L2 (platform) for infrastructure services

dependency "platform" {
  config_path = "../2.platform"

  # skip_outputs = true is required for Atlantis compatibility
  # Atlantis runs each project in isolation, so L2 outputs are not accessible
  # Real values come from terraform_remote_state data source in *.tf files
  skip_outputs = true

  mock_outputs = {
    vault_address = "http://vault.platform.svc.cluster.local:8200"
  }
  mock_outputs_allowed_terraform_commands = ["validate", "plan"]
}

# =============================================================================
# Layer-Specific Providers
# =============================================================================
# Common providers (kubernetes, helm, vault, random) are generated by root terragrunt.hcl

generate "layer_providers" {
  path      = "providers_layer.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOF
    # L4 Apps Layer-Specific Providers
    # All common providers (kubernetes, helm, vault, kubectl) are generated by root terragrunt.hcl
    # No layer-specific providers needed for L4
  EOF
}

# =============================================================================
# Layer-Specific Required Providers
# =============================================================================
# Common providers (kubernetes, helm, vault, random) defined in root terragrunt.hcl

generate "layer_required_providers" {
  path      = "versions.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOF
    terraform {
      required_version = ">= 1.11.0"

      required_providers {
        # Common providers (from root terragrunt.hcl)
        kubernetes = {
          source  = "hashicorp/kubernetes"
          version = "~> 2.0"
        }
        helm = {
          source  = "hashicorp/helm"
          version = "~> 2.0"
        }
        vault = {
          source  = "hashicorp/vault"
          version = "~> 4.0"
        }
        random = {
          source  = "hashicorp/random"
          version = "~> 3.6"
        }
        kubectl = {
          source  = "alekc/kubectl"
          version = "~> 2.0"
        }
        # L4 has no layer-specific providers
      }
    }
  EOF
}
