name: Deploy Application

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - dev
          - test
          - staging
          - prod
      version:
        description: 'Version/tag to deploy'
        required: false
        default: 'latest'

  push:
    branches:
      - main
    paths:
      - 'compose/**'
      - 'scripts/deploy/**'

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment || 'staging' }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'staging' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          echo "ENVIRONMENT=${{ inputs.environment || 'staging' }}" >> $GITHUB_ENV
          echo "VERSION=${{ inputs.version || 'latest' }}" >> $GITHUB_ENV

      - name: Export secrets from Infisical
        uses: Infisical/action@v1
        with:
          client-id: ${{ secrets.INFISICAL_CLIENT_ID }}
          client-secret: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          environment: ${{ env.ENVIRONMENT }}
          project-id: ${{ secrets.INFISICAL_PROJECT_ID }}
          secret-type: dotenv
          path: .env.${{ env.ENVIRONMENT }}

      - name: Validate Docker Compose config
        run: |
          docker compose \
            -f compose/base.yml \
            -f compose/${{ env.ENVIRONMENT }}.yml \
            --env-file .env.${{ env.ENVIRONMENT }} \
            config > /dev/null

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          # Copy files to server
          scp -r compose scripts .env.${{ env.ENVIRONMENT }} \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/opt/truealpha/
          
          # Run deployment script
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "cd /opt/truealpha && \
             ./scripts/deploy/deploy.sh ${{ env.ENVIRONMENT }} ${{ env.VERSION }}"

      - name: Verify deployment
        run: |
          # Wait for services to be healthy
          sleep 30
          
          # Check health endpoint
          DOMAIN=${{ env.ENVIRONMENT == 'prod' && vars.DOMAIN || format('{0}.{1}', env.ENVIRONMENT, vars.DOMAIN) }}
          curl -f https://api.$DOMAIN/health || exit 1

      - name: Notify on success
        if: success()
        run: |
          echo "✅ Deployment to ${{ env.ENVIRONMENT }} completed successfully!"

      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Deployment to ${{ env.ENVIRONMENT }} failed!"
