name: Terraform Plan/Apply (Cloudflare + VPS)

on:
  pull_request:
    paths:
      - 'terraform/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to plan/apply'
        required: true
        type: choice
        options: [staging, test, prod]
      action:
        description: 'Terraform action'
        required: true
        type: choice
        options: [plan, apply]

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: Terraform ${{ inputs.action || 'plan' }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'staging' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/envs/${{ inputs.environment || 'staging' }}

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform/envs/${{ inputs.environment || 'staging' }}

      - name: Terraform Plan
        id: plan
        run: |
          if [ ! -f terraform.tfvars ]; then echo "terraform.tfvars missing" && exit 1; fi
          terraform plan \
            -var-file=terraform.tfvars \
            -out=tfplan \
            -no-color
        working-directory: terraform/envs/${{ inputs.environment || 'staging' }}
        env:
          TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Comment Plan on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const output = `#### Terraform Plan 📝
            
            <details><summary>Show Plan</summary>
            
            \`\`\`
            ${{ steps.plan.outputs.stdout }}
            \`\`\`
            
            </details>
            
            *Pusher: @${{ github.actor }}, Environment: ${{ github.event.inputs.environment || 'dev' }}*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });

      - name: Terraform Apply
        if: |
          (github.event_name == 'workflow_dispatch' && inputs.action == 'apply')
        run: terraform apply -auto-approve tfplan
        working-directory: terraform/envs/${{ inputs.environment || 'staging' }}

      - name: Terraform Output
        if: success()
        run: terraform output
        working-directory: terraform/envs/${{ inputs.environment || 'staging' }}
