name: Terraform Plan and Apply

on:
  pull_request:
    paths:
      - 'terraform/**'
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to apply changes'
        required: true
        type: choice
        options:
          - dev
          - test
          - staging
          - prod
      action:
        description: 'Terraform action'
        required: true
        type: choice
        options:
          - plan
          - apply

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  terraform:
    name: Terraform ${{ github.event.inputs.action || 'plan' }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}
    
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Configure Terraform backend
        env:
          TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
        run: |
          cat > backend-config.tfbackend <<EOF
          bucket = "$TF_STATE_BUCKET"
          key    = "envs/${{ github.event.inputs.environment || 'dev' }}/terraform.tfstate"
          region = "us-east-1"
          encrypt = true
          EOF

      - name: Terraform Init
        run: terraform init -backend-config=backend-config.tfbackend
        working-directory: terraform/envs/${{ github.event.inputs.environment || 'dev' }}

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform/envs/${{ github.event.inputs.environment || 'dev' }}

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan \
            -var-file=terraform.tfvars \
            -out=tfplan \
            -no-color
        working-directory: terraform/envs/${{ github.event.inputs.environment || 'dev' }}
        env:
          TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Comment Plan on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const output = `#### Terraform Plan ðŸ“
            
            <details><summary>Show Plan</summary>
            
            \`\`\`
            ${{ steps.plan.outputs.stdout }}
            \`\`\`
            
            </details>
            
            *Pusher: @${{ github.actor }}, Environment: ${{ github.event.inputs.environment || 'dev' }}*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });

      - name: Terraform Apply
        if: |
          (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply') ||
          (github.event_name == 'push' && github.ref == 'refs/heads/main')
        run: terraform apply -auto-approve tfplan
        working-directory: terraform/envs/${{ github.event.inputs.environment || 'dev' }}

      - name: Terraform Output
        if: success()
        run: terraform output
        working-directory: terraform/envs/${{ github.event.inputs.environment || 'dev' }}
