# =============================================================================
# ClickHouse User & Database Management for SigNoz
# Purpose: Create dedicated user and databases for SigNoz observability stack
# =============================================================================

# Read SigNoz credentials from Vault (generated by L2)
data "vault_kv_secret_v2" "signoz_clickhouse" {
  mount = data.terraform_remote_state.l2_platform.outputs.vault_kv_mount
  name  = data.terraform_remote_state.l2_platform.outputs.vault_db_secrets["signoz"]

  lifecycle {
    precondition {
      condition     = can(data.terraform_remote_state.l2_platform.outputs.vault_db_secrets["signoz"])
      error_message = "L2 platform state missing vault_db_secrets['signoz']. Run L2 apply first."
    }
  }
}

# Create SigNoz User
resource "clickhousedbops_user" "signoz" {
  name     = "signoz"
  password = data.vault_kv_secret_v2.signoz_clickhouse.data["password"]
}

# Create SigNoz Databases
resource "clickhousedbops_database" "signoz_traces" {
  name = "signoz_traces"
}

resource "clickhousedbops_database" "signoz_metrics" {
  name = "signoz_metrics"
}

resource "clickhousedbops_database" "signoz_logs" {
  name = "signoz_logs"
}

# Grant Privileges
# signoz user needs ALL on signoz_* databases
resource "clickhousedbops_grant_privilege" "signoz_traces" {
  user      = clickhousedbops_user.signoz.name
  privilege = "ALL"
  database  = clickhousedbops_database.signoz_traces.name
  table     = "*"
}

resource "clickhousedbops_grant_privilege" "signoz_metrics" {
  user      = clickhousedbops_user.signoz.name
  privilege = "ALL"
  database  = clickhousedbops_database.signoz_metrics.name
  table     = "*"
}

resource "clickhousedbops_grant_privilege" "signoz_logs" {
  user      = clickhousedbops_user.signoz.name
  privilege = "ALL"
  database  = clickhousedbops_database.signoz_logs.name
  table     = "*"
}
