# Production Environment Override
# 生产环境，最高安全性和可靠性

services:
  backend:
    labels:
      - "traefik.http.routers.backend-prod.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.backend-prod.tls=true"
      - "traefik.http.routers.backend-prod.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.backend-security.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.backend-security.headers.stsIncludeSubdomains=true"
      - "traefik.http.routers.backend-prod.middlewares=backend-security"
    environment:
      - DEBUG=false
      - LOG_LEVEL=WARNING
      - SENTRY_DSN=${SENTRY_DSN}
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  neo4j:
    volumes:
      - /mnt/data/prod/neo4j:/data
      - /mnt/backup/prod/neo4j:/backup
    environment:
      - NEO4J_dbms_memory_heap_max__size=4G
      - NEO4J_dbms_logs_query_enabled=true
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 4G
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

  postgres:
    volumes:
      - /mnt/data/prod/postgres:/var/lib/postgresql/data
      - /mnt/backup/prod/postgres:/backup
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

  celery-worker:
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '1'
          memory: 1G

  flower:
    labels:
      - "traefik.http.routers.flower-prod.rule=Host(`flower.${DOMAIN}`)"
      - "traefik.http.routers.flower-prod.tls=true"
      - "traefik.http.middlewares.flower-auth.basicauth.users=${FLOWER_BASIC_AUTH_HASH}"
      - "traefik.http.routers.flower-prod.middlewares=flower-auth"
