# Staging Environment Override
# 预发布环境，使用生产 dump 数据

services:
  backend:
    labels:
      - "traefik.http.routers.backend-staging.rule=Host(`staging.${DOMAIN}`)"
      - "traefik.http.routers.backend-staging.tls=true"
      - "traefik.http.routers.backend-staging.tls.certresolver=letsencrypt"
    environment:
      - DEBUG=false
      - LOG_LEVEL=INFO
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  neo4j:
    volumes:
      - /mnt/data/staging/neo4j:/data
      - /mnt/backup/staging/neo4j:/backup
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  postgres:
    volumes:
      - /mnt/data/staging/postgres:/var/lib/postgresql/data
      - /mnt/backup/staging/postgres:/backup
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
