# =============================================================================
# L3 Data Layer Configuration (Shared by All Environments)
# CI Trigger: Force validation run
# =============================================================================
# Provides data services (PostgreSQL, ClickHouse, Redis, ArangoDB)
# Environment is auto-detected from directory path (envs/{env}/data)

include "root" {
  path = find_in_parent_folders()
}

# =============================================================================
# Layer Dependencies
# =============================================================================
# L3 depends on L2 platform for infrastructure services

dependency "platform" {
  config_path = "../../../platform"

  # skip_outputs = true is required for Atlantis compatibility
  # Atlantis runs each project in isolation, so L2 outputs are not accessible
  # Real values come from terraform_remote_state data source in *.tf files
  skip_outputs = true

  # Mock outputs for plan-time (before L2 is applied)
  mock_outputs = {
    vault_address = "http://vault.platform.svc.cluster.local:8200"
  }
  mock_outputs_allowed_terraform_commands = ["validate", "plan"]
}


# =============================================================================
# Layer-Specific Providers
# =============================================================================
# Common providers (kubernetes, helm, vault) are generated by root terragrunt.hcl

generate "layer_providers" {
  path      = "providers_layer.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOF
    # L3 Data Layer-Specific Providers
    # Common providers (kubernetes, helm, vault, kubectl) are generated by root terragrunt.hcl
    # 
    # NOTE: clickhousedbops provider is configured in 3.clickhouse.tf, not here.
    # This is because the provider needs the clickhouse password from vault_kv_secret_v2
    # resource, which creates a dependency that can't be resolved at terragrunt level.
  EOF
}

# =============================================================================
# Layer-Specific Required Providers
# =============================================================================
# Common providers (kubernetes, helm, vault, random) defined in root terragrunt.hcl

generate "layer_required_providers" {
  path      = "versions.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOF
    terraform {
      required_version = ">= 1.11.0"

      required_providers {
        # Common providers (from root terragrunt.hcl)
        kubernetes = {
          source  = "hashicorp/kubernetes"
          version = "~> 2.0"
        }
        helm = {
          source  = "hashicorp/helm"
          version = "~> 2.0"
        }
        vault = {
          source  = "hashicorp/vault"
          version = "~> 4.0"
        }
        random = {
          source  = "hashicorp/random"
          version = "~> 3.6"
        }
        kubectl = {
          source  = "alekc/kubectl"
          version = "~> 2.0"
        }

        # L3 Data layer-specific providers
        time = {
          source  = "hashicorp/time"
          version = "~> 0.9"
        }
        clickhousedbops = {
          source  = "ClickHouse/clickhousedbops"
          version = "~> 0.1"
        }
      }
    }
  EOF
}

