"""/verify command handler (post-merge drift scan)."""

from ..config import get_layers_by_order
from ..core.terraform import TerraformRunner, PlanResult
from ..core.github import GitHubClient


def run(args) -> int:
    """Execute verify command (drift scan + optional apply).

    Args:
        args.apply: If True, apply when drift detected
        args.pr: Optional merged PR number for result posting
    """
    print("🔍 Starting drift verification...")

    layers = get_layers_by_order()
    drift_detected = []
    errors = []

    # Phase 1: Parallel drift scan (conceptually - sequential in Python)
    print("\n📋 Phase 1: Drift Scan")
    for layer in layers:
        print(f"  Scanning {layer.name}...", end=" ", flush=True)

        runner = TerraformRunner(layer)

        # Init
        init_result = runner.init()
        if not init_result.success:
            print(f"❌ Init failed")
            errors.append(layer.name)
            continue

        # Plan
        plan_result = runner.plan(detailed_exitcode=True)
        if plan_result.plan_result == PlanResult.NO_CHANGES:
            print("✅ No drift")
        elif plan_result.plan_result == PlanResult.HAS_CHANGES:
            print("⚠️ Drift detected")
            drift_detected.append(layer)
        else:
            print("❌ Error")
            errors.append(layer.name)

    # Phase 2: Sequential apply if requested
    applied = []
    if args.apply and drift_detected:
        print("\n🚀 Phase 2: Sequential Apply")
        for layer in drift_detected:
            print(f"  Applying {layer.name}...", end=" ", flush=True)

            runner = TerraformRunner(layer)
            apply_result = runner.apply(auto_approve=True)

            if apply_result.success:
                print("✅ Done")
                applied.append(layer.name)
            else:
                print("❌ Failed")
                print(f"    Error: {apply_result.stderr[:500] if apply_result.stderr else 'Unknown error'}")
                errors.append(layer.name)
                break  # Stop on first error

    # Post results to merged PR if specified
    if args.pr:
        try:
            gh = GitHubClient()
            body = _build_summary(layers, drift_detected, applied, errors)
            gh.create_comment(args.pr, body)
            print(f"\n📝 Posted summary to PR #{args.pr}")
        except Exception as e:
            print(f"\n⚠️ Failed to post summary: {e}")

    # Final summary
    print("\n" + "=" * 50)
    print("📊 Verification Summary")
    print("=" * 50)
    print(f"  Layers scanned: {len(layers)}")
    print(f"  Drift detected: {len(drift_detected)}")
    print(f"  Applied: {len(applied)}")
    print(f"  Errors: {len(errors)}")

    return 1 if errors else 0


def _build_summary(
    layers: list, drift_detected: list, applied: list, errors: list
) -> str:
    """Build markdown summary for PR comment."""
    lines = [
        "## 🔍 Post-Merge Verification",
        "",
        "| Layer | Drift | Applied | Status |",
        "|:---|:---:|:---:|:---:|",
    ]

    for layer in layers:
        has_drift = layer in drift_detected
        was_applied = layer.name in applied
        has_error = layer.name in errors

        drift_icon = "⚠️" if has_drift else "✅"
        apply_icon = "✅" if was_applied else ("❌" if has_error else "-")
        status = "❌" if has_error else "✅"

        lines.append(
            f"| {layer.name} | {drift_icon} | {apply_icon} | {status} |"
        )

    lines.extend(
        [
            "",
            "---",
            "🤖 Generated by CI Pipeline",
        ]
    )

    return "\n".join(lines)
